name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install

    - name: Install Calibre
      run: |
        sudo -v
        sudo apt-get update -y && sudo apt-get install -y libegl1 libopengl0 fonts-noto graphviz fonts-noto-cjk
        wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

    - name: Build docs
      run: npm run build
      env:
        CHROMIUM_FLAGS: --no-sandbox

    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: _book/

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.pull_request.body }}
        tag_name: ${{ github.event.pull_request.title }}
        generate_release_notes: true
        files: target/hoge.jar

    - name: Generate PDF
      run: npx honkit pdf ./ ./output.pdf

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: documents
        path: ./output.pdf
